#!/usr/bin/perl

sub dist {
	my ($x1, $y1) = split(/,/, $fields[$_[0] + 2]);
	my ($x2, $y2) = split(/,/, $fields[$_[1] + 2]);

	my $dist = sqrt(($x1 - $x2) * ($x1 - $x2) + ($y1 - $y2) * ($y1 - $y2));
	return $dist;
}

sub max {
	my $biggest = $_[0];
	for my $f (@_) {
		if ($f > $biggest) {
			$biggest = $f;
		}
	}
	return $biggest;
}

sub min {
	my $biggest = $_[0];
	for my $f (@_) {
		if ($f < $biggest) {
			$biggest = $f;
		}
	}
	return $biggest;
}

while (<>) {
	next if /^#/;
	chomp;
	@fields = split(/ /);

	$vert_angle = dist(27, 33) / dist(33, 8);
	$horiz_angle = dist(27, 0) / dist(27, 16);
	$scale_angle = dist(16, 0) / dist(27, 8);
	print "$horiz_angle,$vert_angle,$scale_angle,";

	print "$_\n";
}
