#!/usr/bin/perl

open(MEN, "/usr/local/share/dlib-siblings-brothers-mean-stddev.encoded") || die;
while (<MEN>) {
	next if /^#/;
	chomp;
	@men = split(/ /);

	for ($i = 0; $i <= $#men; $i++) {
		($men_mean[$i], $men_stddev[$i]) = split(/,/, $men[$i]);
	}
}
close(MEN);

open(WOMEN, "/usr/local/share/dlib-siblings-sisters-mean-stddev.encoded") || die;
while (<WOMEN>) {
	next if /^#/;
	chomp;
	@women = split(/ /);

	for ($i = 0; $i <= $#women; $i++) {
		($women_mean[$i], $women_stddev[$i]) = split(/,/, $women[$i]);
	}
}
close(WOMEN);

while (<>) {
	chomp;
	next if /^#/;

	@fields = split(/ /);

	for ($i = 8; $i < 8 + 128; $i++) {
		$fields[$i] = ($fields[$i] - $men_mean[$i]) / $men_stddev[$i] * $women_stddev[$i] + $women_mean[$i];
	}

	print "$fields[0]";

	for ($i = 1; $i < 8; $i++) {
		print " $fields[$i]";
	}

	for ($i = 8; $i < 8 + 128; $i++) {
		printf(" %.6f", $fields[$i]);
	}

	for ($i = 128 + 8; $i <= $#fields; $i++) {
		print " $fields[$i]";
	}

	print "\n";
}
