#!/usr/bin/perl

open(IN, "/usr/local/share/dlib-noglam-mean-stddev.encoded") || die;
while (<IN>) {
	next if /^#/;
	chomp;
	@fields = split(/ /);

	for ($i = 0; $i <= $#fields; $i++) {
		($no_mean[$i], $no_stddev[$i]) = split(/,/, $fields[$i]);
	}
}
close(IN);

open(IN, "/usr/local/share/dlib-glam-mean-stddev.encoded") || die;
while (<IN>) {
	next if /^#/;
	chomp;
	@fields = split(/ /);

	for ($i = 0; $i <= $#fields; $i++) {
		($yes_mean[$i], $yes_stddev[$i]) = split(/,/, $fields[$i]);
	}
}
close(IN);

while (<>) {
	chomp;
	next if /^#/;

	@fields = split(/ /);

	for ($i = 8; $i < 8 + 128; $i++) {
		$fields[$i] = ($fields[$i] - $no_mean[$i]) / $no_stddev[$i] * $yes_stddev[$i] + $yes_mean[$i];
	}

	for ($i = 0; $i < 8; $i++) {
		print "$fields[$i] ";
	}

	for ($i = 8; $i < 8 + 128; $i++) {
		printf("%.6f ", $fields[$i]);
	}

	print "$fields[128 + 8]\n";
}
