#!/usr/bin/perl

mkdir("crops");

while (<>) {
	chomp;
	next if /#/;
	@fields = split(/ /);

	$bn = $fields[$#fields];
	$bn =~ s/.*\///;

	for ($i = 0; $i <= $#fields; $i++) {
		if ($fields[$i] =~ /^(\d+),(\d+)/) {
			$fields[$i] = sprintf("%d,%d", $1 + 200, $2 + 200);
		}
	}

	$cmd = "convert -size 600x1600 xc:white \\( -bordercolor white -border 200 $fields[$#fields] -virtual-pixel transparent +distort Affine '$fields[27 + 2] 300,200 $fields[8 + 2] 300,300' -crop 800x1600+0+0 +repage \\) -composite crops/$bn";
	print "$cmd\n";
	system "$cmd";
}

