#!/bin/sh

case "$1" in
	"")
		dir=matched
	;;

	*)
		dir=$1
	;;
esac

mkdir -p "$dir"

IFS='	'
while read score fname bbox fname2 bbox2
do
	out="$dir/$score-$(basename "$fname").jpg"
	if test -f "$out"
	then :
	else
		convert -crop "$bbox" "$fname" "$out"
	fi
done
