#!/usr/bin/perl

$pi = 4 * atan2(1, 1);

if ($ARGV[0] eq '-p') {
	shift @ARGV;
	$ps = 1;
}

if ($ps) {
	print ".01 setlinewidth\n";
}

while (<>) {
	next if /^#/;
	($id, $bbox, @rest) = split(/ /);

	($x1, $y1) = split(/,/, $rest[27]); # top of nose
	($x2, $y2) = split(/,/, $rest[8]); # top of chin
	($x3, $y3) = split(/,/, $rest[39]); # outer left eye
	($x4, $y4) = split(/,/, $rest[42]); # outer right eye

	$xd4 = $x4 - $x1;
	$yd4 = $y4 - $y1;
	$d4 = sqrt($xd4 * $xd4 + $yd4 * $yd4);

	$xd3 = $x3 - $x1;
	$yd3 = $y3 - $y1;
	$d3 = sqrt($xd3 * $xd3 + $yd3 * $yd3);

	if (0) {
		if ($d4 > $d3) {
			$flop = 1;
			next;
		} else {
			$flop = 0;
		}
	}

	$angle = atan2($y1 - $y2, $x1 - $x2);

	$xd = $x1 - $x2;
	$yd = $y1 - $y2;
	$dist = sqrt($xd * $xd + $yd * $yd);

	for ($i = 0; $i < 68; $i++) {
		($x, $y) = split(/,/, $rest[$i]);

		# translate to be relative to top of nose
		$x = $x - $x1;
		$y = $y - $y1;

		# rectangular to polar
		$ang = atan2($y, $x);
		$d = sqrt($y * $y + $x * $x);

		# rotate to vertical
		$ang -= $angle - -$pi/2;

		# polar to rectangular
		$x = $d * cos($ang);
		$y = $d * sin($ang);

		# XXX No this actually needs to flop the corresponding points
		# not just the sign
		if (0 && $flop) {
			$x = -$x;
		}

		$px[$i] = $x;
		$py[$i] = $y;

		$sx[$i] += $x / $dist;
		$sy[$i] += $y / $dist;
		$count[$i]++;
	}
}

if ($ps) {
	print "/Helvetica findfont 12 scalefont setfont\n";

	for ($i = 0; $i < 68; $i++) {
		$x = $sx[$i] / $count[$i];
		$y = $sy[$i] / $count[$i];

		printf("%.3f %.3f ", $x * 250 + 306, 612 - ($y * 250 + 306));
		if ($i == 0 || $i == 17 || $i == 22 || $i == 27 || $i == 31 || $i == 36 || $i == 40 || $i == 42 || $i == 48) {
			print "moveto ";
		} else {
			print "lineto ";
		}
	}

	print "stroke\n";

	for ($i = 0; $i < 68; $i++) {
		$x = $sx[$i] / $count[$i];
		$y = $sy[$i] / $count[$i];

		printf("%.3f %.3f moveto ($i) show stroke\n", $x * 250 + 306, 612 - ($y * 250 + 306));
	}
} else {
	for ($i = 0; $i < 68; $i++) {
		$x = $sx[$i] / $count[$i];
		$y = $sy[$i] / $count[$i];

		printf("{ %.3f, %.3f },\n", $x * 450 + 306, ($y * 450 + 106));
	}
}
