#!/usr/bin/perl

while (<>) {
	chomp;
	@fields = split(/ /, $_, 128 + 8 + 1);

	for ($i = 0; $i < 128; $i++) {
		$metric{$fields[128 + 8]}{$fields[0]}{8 + $i} = $fields[8 + $i];
	}

	$max{$fields[128 + 8]} = $fields[0];
}

# https://www.geeksforgeeks.org/program-find-correlation-coefficient/
for $i (keys(%metric)) {
	if ($max{$i} == 1) {
		for ($j = 0; $j < 128; $j++) {
			$x = $metric{$i}{0}{$j + 8};
			$y = $metric{$i}{1}{$j + 8};

			$xsum{$j} += $x;
			$ysum{$j} += $y;
			$xysum{$j} += $x * $y;

			$x2sum{$j} += $x * $x;
			$y2sum{$j} += $y * $y;
		}

		$count++;
	}
}

for ($j = 0; $j < 128; $j++) {
	$r = ($count * $xysum{$j} - $xsum{$j} * $ysum{$j}) /
		sqrt(($count * $x2sum{$j} - $xsum{$j} * $xsum{$j})
		* ($count * $y2sum{$j} - $ysum{$j} * $ysum{$j}));
	print "$r ";
}

print "\n";
